language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=notifications
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - which php
  - more $(which pecl)
  - which phpize
  - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list
  - ./occ app:enable $APP_NAME
  - ./occ app:list

  # Setup behat for acceptance tests
  - cd apps/$APP_NAME/
  - cd tests/acceptance/
  - sh -c "if [ '$ACCEPTANCE' = '1' ]; then composer install; fi"
  - cd ../../

script:
  # Test the app
  - sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
  - cd ../../
  - sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests/Unit
  - sh -c "if [ '$ACCEPTANCE' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then ../../../../lib/composer/bin/phpunit --configuration phpunit.xml; fi"
  - cd ../..

  # Acceptance tests
  - cd tests/acceptance
  - sh -c "if [ '$ACCEPTANCE' = '1' ]; then bash run.sh; fi"
  - cd ../..

  # Create coverage report
  - cd tests/Unit
  - sh -c "if [ '$ACCEPTANCE' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$ACCEPTANCE' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  - cd ../..

  # Run Javascript unit tests
#  - cd tests/js
#  - sh -c "if [ '$JSTESTS' = '1' ]; then npm install --deps; node_modules/karma/bin/karma start karma.config.js --single-run; fi"
#  - cd ../
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
matrix:
  include:
    - php: 5.6
      env: DB=oracle
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql CODECHECK=1
    - php: 5.6
      env: DB=mysql CODECHECK=2
    - php: 5.6
      env: DB=mysql ACCEPTANCE=1
    - php: 7.1
      env: DB=oracle CORE_BRANCH=master
    - php: 7.1
      env: DB=mysql CORE_BRANCH=master
    - php: 7.1
      env: DB=pgsql CORE_BRANCH=master
    - php: 7.1
      env: DB=mysql CODECHECK=1 CORE_BRANCH=master
    - php: 7.1
      env: DB=mysql CODECHECK=2 CORE_BRANCH=master
    - php: 7.1
      env: DB=mysql ACCEPTANCE=1 CORE_BRANCH=master
  allow_failures:
    - env: DB=mysql;CODECHECK=2
  fast_finish: true
